djangoexperimentalversion/TFT/TFT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('playground/', include('playground.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    ]

djangoexperimentalversion/TFT/playground/urls.py
from django.urls import path
from . import views

#URLConf
app_name = 'polls'
urlpatterns = [\
    path('main/', views.main),
    path('main/calculator/', views.calculator),
    path('main/calculator/basicmath/', views.basicmath),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

djangoexperimentalversion/TFT/playground/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

djangoexperimentalversion/TFT/playground/forms.py
from django import forms
from django.forms import ModelForm

djangoexperimentalversion/TFT/playground/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect, request
from django.template import loader
from .models import Question, Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone
import subprocess
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())    


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def main(request):
    #subprocess.Popen(["rm", "-r", "utils.logging"])
    return render(request, 'apphub/main.html')
        
def calculator(request):
    return render(request, 'apphub/calculator.html')

def basicmath(request):
    return render(request, 'apphub/basicmath.html')

djangoexperimentalversion/TFT/playground/templates/apphub/basicmath.html
<!DOCTYPE html>
<html>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <body>
        <br>
        <br>Addition <br> 1st number
        <input type="text" id="addnum1" name="name" required minlength="1" maxlength="20" size="10">
        <br> Second Number
        <input type="text" id="addnum2" name="name" required minlength="1" maxlength="20" size="10">
        <br>
        <button type="button" onclick=GetADDNum()>ADD</button>
    </body>
    <script>
        function GetADDNum() {
            ADDNUM1 = document.getElementById('addnum1').value;
            //alert(ADDNUM1);
            ADDNUM2 = document.getElementById('addnum2').value;
            //alert(ADDNUM2);
            alert(+ADDNUM1 + +ADDNUM2)
        }
    </script>

    <body>
        <br>
        <br>Subtraction <br> 1st number
        <input type="text" id="subnum1" name="name" required minlength="1" maxlength="20" size="10">
        <br> Second Number
        <input type="text" id="subnum2" name="name" required minlength="1" maxlength="20" size="10">
        <br>
        <button type="button" onclick=GetSUBNum()>SUB</button>
    </body>
    <script>
        function GetSUBNum() {
            SUBNUM1 = document.getElementById('subnum1').value;
            //alert(SUBNUM1);
            SUBNUM2 = document.getElementById('subnum2').value;
            //alert(SUBNUM2);
            alert(+SUBNUM1 - +SUBNUM2)
        }
    </script>

    <body>
        <br>
        <br>Multiplication <br> 1st number
        <input type="text" id="mulnum1" name="name" required minlength="1" maxlength="20" size="10">
        <br> Second Number
        <input type="text" id="mulnum2" name="name" required minlength="1" maxlength="20" size="10">
        <br>
        <button type="button" onclick=GetMULNum()>MUL</button>
    </body>
    <script>
        function GetMULNum() {
            MULNUM1 = document.getElementById('mulnum1').value;
            //alert(MULNUM1);
            MULNUM2 = document.getElementById('mulnum2').value;
            //alert(MULNUM2);
            alert(+MULNUM1 * +MULNUM2)
        }
</script>

    <body>
        <br>
        <br>Division <br> 1st number
        <input type="text" id="divnum1" name="name" required minlength="1" maxlength="20" size="10">
        <br> Second Number
        <input type="text" id="divnum2" name="name" required minlength="1" maxlength="20" size="10">
        <br>
        <button type="button" onclick=GetDIVNum()>DIV</button>
    </body>
    <script>
        function GetDIVNum() {
            DIVNUM1 = document.getElementById('divnum1').value;
            //alert(DIVNUM1);
            DIVNUM2 = document.getElementById('divnum2').value;
            //alert(DIVNUM2);
            alert(+DIVNUM1 / +DIVNUM2)
        }
    </script>
    <body>
        <br>
        <br>
        <a href="javascript:history.back()">Back</a>
    </body>
</html>

djangoexperimentalversion/TFT/playground/templates/apphub/calculator.html
<!DOCTYPE html>
<html>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <body>
        <p>
            Welcome to the Calculator<br>
            <a href="basicmath/">Basic Math<br></a>
            <a href="javascript:history.back()">Back</a>
        </p>
    </body>
</html>

djangoexperimentalversion/TFT/playground/templates/apphub/hello.html
<!DOCTYPE html>
<html>
    <body>
        {% if name%}
        <h1>Hello {{ name }}</h1>
        {% else%}
        <h1> Hello World</h1>
        {% endif %}
    </body>
</html>

djangoexperimentalversion/TFT/playground/templates/apphub/logincomplete.html
<html>
    <body>
        login complete
    </body>
</html>

djangoexperimentalversion/TFT/playground/templates/apphub/main.html
<!DOCTYPE html>
<html>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <body>
        <p>
            NOTE Mobile is different from PC. For best performance run on PC. <br> <br>
            <a href="calculator/">calculator</a><br>
            <br>
            <a href="javascript:history.back()">Back</a> <br>
        </p>
        <p id="output">

        </p>
        <script>
            function sayHello() {
                alert("Hello "+document.cookie)
            }

        </script>
    </body>
</html>

djangoexperimentalversion/TFT/playground/templates/polls/detail.html
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

djangoexperimentalversion/TFT/playground/templates/polls/index.html
<html>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<body>
    <p>
        Hello and welcome to the website <br>
        this will take you to the app hub  <a href="main/">Link to the app hub</a><br>
        <br>This is the poll section
    </p>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

djangoexperimentalversion/TFT/playground/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:index' %}">Back</a>